### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by JoshLRR** [kmnunley/Blender-GCode-Importer#1]
Hey!

I'm excited about this script and can't get it working, but I seem to be running into a bug regarding the Z values as the g-code is being parsed (at least that's what it looks like at first glance). The error occurs on attempting a .gcode import and doesn't output anything, yet. Here's the error:

Python: Traceback (most recent call last):
  File "/Users/joshualo/Library/Application Support/Blender/2.93/scripts/addons/gcode_importer.py", line 126, in execute
    import_gcode(self.filepath)
  File "/Users/joshualo/Library/Application Support/Blender/2.93/scripts/addons/gcode_importer.py", line 110, in import_gcode
    create_paths(gcode_lines)
  File "/Users/joshualo/Library/Application Support/Blender/2.93/scripts/addons/gcode_importer.py", line 61, in create_paths
    z = float(param[1:])
ValueError: could not convert string to float: ''

location: <unknown location>:-1

Thanks!

**Comment by kmnunley** [comment]
What slicer are you using to create the Gcode file? So far I've only tested with Prusa Slicer. Link the gcode file as well if you can.

**Comment by JoshLRR** [comment]
[Plain Cupholder Slicer File.txt](https://github.com/kmnunley/Blender-GCode-Importer/files/10388306/Plain.Cupholder.Slicer.File.txt)

I'm also using PrusaSlicer, but I just realized that I have some custom starting gcode and there's a chance that could be affecting things. Needed to convert to a txt file to make github happy, so apologies for that.

**Comment by kmnunley** [comment]
Fixed and verified working with provided gcode. Download the latest version for the fix.

**Comment by JoshLRR** [comment]
Can confirm the changes work on my end as well. Thanks for the speedy fix!
